Visual Identity
fga-eps-mds/2019.1-hubcare-docs pull request #61
Opened 2019-04-17 00:04 UTC by Brian2397

## Issue #54 

## Description

Describes the look of HubCare

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2019-04-17 00:05 UTC, Brian2397 commented
@filipetoyoshima Please, check the Visual Identity

2019-04-17 00:47 UTC, filipetoyoshima requested changes
Notei, ainda, que não foram específicados os estilos de gráficos, como pedido da issue #54

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +***
Não é necessário que toda informação esteja contida em imagens. Inclusive, isso na maioria das vezes não é recomendado. Escreva os títulos e textos em markdown mesmo e atenha apenas o necessário às imagens, como Cores e Logo.

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +![logo](logo1.png)
Falta explicação sobre a mensagem que a Logo tem a intenção de passar.

Parear com o @FranciscoHeronildo para obter outras formas da logo úteis da logo, como por exemplo um favicon e uma versão monocromárica. Tenham em mente que essas são as imagens que vocês utilizarão durante o desenvolvimento do produto. Convém, também, fazer o upload dos arquivos `.svg` utilizados

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +![Apresentação da Paleta](paleta1.png)
Não lembro de ter visto roxo no GitHub. Talvez você esteja confundindo com o ZenHub, não?

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +![Mostruário das Cores](paleta2.png)
É importante mencionar onde cada cor deve ser usada. Por exemplo, a verde será utilizada para colorir textos? Ou apenas gráficos?

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +![Tipografia](tipografia1.png)
Por que você está citando a tipografia do GitHub? É importante deixar isso explícito ao leitor.

Onde o GitHub usa cada uma dessas fontes? É pra header? É para texto longo? É importante citarmos a fonte de Emoji?

Por que a escolha por essa fonte no HubCare?

2019-04-17 00:47 UTC, filipetoyoshima commented on docs/project/visual-identity/README.md
> +![Abhaya](abhaya1.png)
Tipografias costumam ser um pouco mais complexas do que apenas uma fonte. Normalmente escolhemos uma para Header e outra para textos. Além disso, é necessário especificar o tamanho e a cor de cada fonte. Para isso, recomendo que atente às diretrizes de acessibilidade, pois letras com pouco contraste com o fundo ou muito pequenas não são acessíveis a pessoas com dificuldades de visão. Recomendo a leitura: https://webaim.org/resources/contrastchecker/

2019-04-17 23:56 UTC, Brian2397 commented on docs/project/visual-identity/README.md
> +![Abhaya](abhaya1.png)
Pronto, foi adicionado os gráficos

2019-04-18 00:22 UTC, Brian2397 commented
Okay, all the problems have been fixed

2019-04-18 01:40 UTC, filipetoyoshima approved these changes

2019-04-18 01:41 UTC, filipetoyoshima commented
That's enough

2019-04-18 01:41 UTC, merged